//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8789
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.DFacture.Client.Internals {
	using System.Runtime.Serialization;


	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaTFD33", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaTFD33 : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.Timbre33 TimbreField;

		private string codigoField;

		private string mensajeField;

		private string mensajedetalladoField;

		private string ridField;

		private string uuidField;

		private bool validateField;

		private string xmlField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.Timbre33 Timbre {
			get {
				return this.TimbreField;
			}
			set {
				this.TimbreField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensajedetallado {
			get {
				return this.mensajedetalladoField;
			}
			set {
				this.mensajedetalladoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string rid {
			get {
				return this.ridField;
			}
			set {
				this.ridField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string uuid {
			get {
				return this.uuidField;
			}
			set {
				this.uuidField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool validate {
			get {
				return this.validateField;
			}
			set {
				this.validateField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string xml {
			get {
				return this.xmlField;
			}
			set {
				this.xmlField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "Timbre33", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class Timbre33 : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.DateTime FechaTimbradoField;

		private string LeyendaField;

		private string NoCertificadoSATField;

		private string RfcProvCertifField;

		private string SelloCFDField;

		private string SelloSATField;

		private string UUIDField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public System.DateTime FechaTimbrado {
			get {
				return this.FechaTimbradoField;
			}
			set {
				this.FechaTimbradoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string Leyenda {
			get {
				return this.LeyendaField;
			}
			set {
				this.LeyendaField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string NoCertificadoSAT {
			get {
				return this.NoCertificadoSATField;
			}
			set {
				this.NoCertificadoSATField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RfcProvCertif {
			get {
				return this.RfcProvCertifField;
			}
			set {
				this.RfcProvCertifField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string SelloCFD {
			get {
				return this.SelloCFDField;
			}
			set {
				this.SelloCFDField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string SelloSAT {
			get {
				return this.SelloSATField;
			}
			set {
				this.SelloSATField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string UUID {
			get {
				return this.UUIDField;
			}
			set {
				this.UUIDField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaTFD", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaTFD : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.Timbre TimbreField;

		private string codigoField;

		private string mensajeField;

		private string mensajedetalladoField;

		private string uuidField;

		private bool validateField;

		private string xmlField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.Timbre Timbre {
			get {
				return this.TimbreField;
			}
			set {
				this.TimbreField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensajedetallado {
			get {
				return this.mensajedetalladoField;
			}
			set {
				this.mensajedetalladoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string uuid {
			get {
				return this.uuidField;
			}
			set {
				this.uuidField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool validate {
			get {
				return this.validateField;
			}
			set {
				this.validateField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string xml {
			get {
				return this.xmlField;
			}
			set {
				this.xmlField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "Timbre", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class Timbre : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private System.DateTime FechaTimbradoField;

		private string UUIDField;

		private string noCertificadoSATField;

		private string selloCFDField;

		private string selloSATField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public System.DateTime FechaTimbrado {
			get {
				return this.FechaTimbradoField;
			}
			set {
				this.FechaTimbradoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string UUID {
			get {
				return this.UUIDField;
			}
			set {
				this.UUIDField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string noCertificadoSAT {
			get {
				return this.noCertificadoSATField;
			}
			set {
				this.noCertificadoSATField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string selloCFD {
			get {
				return this.selloCFDField;
			}
			set {
				this.selloCFDField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string selloSAT {
			get {
				return this.selloSATField;
			}
			set {
				this.selloSATField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaAcuse", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaAcuse : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string acuseField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string acuse {
			get {
				return this.acuseField;
			}
			set {
				this.acuseField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaRecuperarXML", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaRecuperarXML : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		private string xmlField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string xml {
			get {
				return this.xmlField;
			}
			set {
				this.xmlField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaConsultarTimbres", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaConsultarTimbres : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		private int timbresField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public int timbres {
			get {
				return this.timbresField;
			}
			set {
				this.timbresField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaRegistrarAdquiriente", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaRegistrarAdquiriente : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		private bool validateField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool validate {
			get {
				return this.validateField;
			}
			set {
				this.validateField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaCancelacion", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaCancelacion : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaFirmaManifiesto", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaFirmaManifiesto : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string manifiestoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string manifiesto {
			get {
				return this.manifiestoField;
			}
			set {
				this.manifiestoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaServicio", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaServicio : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "DatosReferencia", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class DatosReferencia : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string RFCEmisorField;

		private string RFCReceptorField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RFCEmisor {
			get {
				return this.RFCEmisorField;
			}
			set {
				this.RFCEmisorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RFCReceptor {
			get {
				return this.RFCReceptorField;
			}
			set {
				this.RFCReceptorField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaSolicitarToken", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaSolicitarToken : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string CaptchaImgBase64Field;

		private bool OperacionField;

		private string TokenField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string CaptchaImgBase64 {
			get {
				return this.CaptchaImgBase64Field;
			}
			set {
				this.CaptchaImgBase64Field = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool Operacion {
			get {
				return this.OperacionField;
			}
			set {
				this.OperacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string Token {
			get {
				return this.TokenField;
			}
			set {
				this.TokenField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaEnviarToken", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaEnviarToken : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.ReferenciasConfirmacion [] ListaConfirmacionField;

		private bool OperacionField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.ReferenciasConfirmacion [] ListaConfirmacion {
			get {
				return this.ListaConfirmacionField;
			}
			set {
				this.ListaConfirmacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool Operacion {
			get {
				return this.OperacionField;
			}
			set {
				this.OperacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "ReferenciasConfirmacion", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class ReferenciasConfirmacion : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string CodigoConfirmacionField;

		private System.DateTime FechaCreacionField;

		private System.DateTime FechaExpiracionField;

		private string RFCEmisorField;

		private string RFCReceptorField;

		private string userField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string CodigoConfirmacion {
			get {
				return this.CodigoConfirmacionField;
			}
			set {
				this.CodigoConfirmacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public System.DateTime FechaCreacion {
			get {
				return this.FechaCreacionField;
			}
			set {
				this.FechaCreacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public System.DateTime FechaExpiracion {
			get {
				return this.FechaExpiracionField;
			}
			set {
				this.FechaExpiracionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RFCEmisor {
			get {
				return this.RFCEmisorField;
			}
			set {
				this.RFCEmisorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RFCReceptor {
			get {
				return this.RFCReceptorField;
			}
			set {
				this.RFCReceptorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string user {
			get {
				return this.userField;
			}
			set {
				this.userField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaConsultarEstatusCFDI", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaConsultarEstatusCFDI : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string EsCancelableField;

		private string EstatusCancelacionField;

		private string codigoField;

		private string estadoField;

		private string mensajeField;

		private bool operacionField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string EsCancelable {
			get {
				return this.EsCancelableField;
			}
			set {
				this.EsCancelableField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string EstatusCancelacion {
			get {
				return this.EstatusCancelacionField;
			}
			set {
				this.EstatusCancelacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string estado {
			get {
				return this.estadoField;
			}
			set {
				this.estadoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool operacion {
			get {
				return this.operacionField;
			}
			set {
				this.operacionField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaCancelacionCFDI", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaCancelacionCFDI : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string EsCancelableField;

		private string EstatusCancelacionField;

		private string codigoField;

		private string estadoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string EsCancelable {
			get {
				return this.EsCancelableField;
			}
			set {
				this.EsCancelableField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string EstatusCancelacion {
			get {
				return this.EstatusCancelacionField;
			}
			set {
				this.EstatusCancelacionField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string estado {
			get {
				return this.estadoField;
			}
			set {
				this.estadoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaConsultarRelacionadosCFDI", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaConsultarRelacionadosCFDI : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string ResultadoField;

		private string UuidConsultadoField;

		private Mictlanix.DFacture.Client.Internals.uuidsRelacionadosHijos UuidsRelacionadosHijosField;

		private Mictlanix.DFacture.Client.Internals.uuidsRelacionadosPadres UuidsRelacionadosPadresField;

		private string codigoField;

		private string mensajeField;

		private bool operacionField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string Resultado {
			get {
				return this.ResultadoField;
			}
			set {
				this.ResultadoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string UuidConsultado {
			get {
				return this.UuidConsultadoField;
			}
			set {
				this.UuidConsultadoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.uuidsRelacionadosHijos UuidsRelacionadosHijos {
			get {
				return this.UuidsRelacionadosHijosField;
			}
			set {
				this.UuidsRelacionadosHijosField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.uuidsRelacionadosPadres UuidsRelacionadosPadres {
			get {
				return this.UuidsRelacionadosPadresField;
			}
			set {
				this.UuidsRelacionadosPadresField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public bool operacion {
			get {
				return this.operacionField;
			}
			set {
				this.operacionField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "uuidsRelacionadosHijos", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class uuidsRelacionadosHijos : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.value [] UuidHijoField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.value [] UuidHijo {
			get {
				return this.UuidHijoField;
			}
			set {
				this.UuidHijoField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "uuidsRelacionadosPadres", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class uuidsRelacionadosPadres : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.value [] UuidPadreField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.value [] UuidPadre {
			get {
				return this.UuidPadreField;
			}
			set {
				this.UuidPadreField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "value", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class value : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string RfcEmisorField;

		private string RfcReceptorField;

		private string UuidField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RfcEmisor {
			get {
				return this.RfcEmisorField;
			}
			set {
				this.RfcEmisorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string RfcReceptor {
			get {
				return this.RfcReceptorField;
			}
			set {
				this.RfcReceptorField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string Uuid {
			get {
				return this.UuidField;
			}
			set {
				this.UuidField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaConsultarPendientesCFDI", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaConsultarPendientesCFDI : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string mensajeField;

		private Mictlanix.DFacture.Client.Internals.uuids [] respuestaField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.uuids [] respuesta {
			get {
				return this.respuestaField;
			}
			set {
				this.respuestaField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "uuids", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class uuids : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string uuidField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string uuid {
			get {
				return this.uuidField;
			}
			set {
				this.uuidField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "RespuestaAceptacionRechazoCFDI", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class RespuestaAceptacionRechazoCFDI : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private Mictlanix.DFacture.Client.Internals.ListaResultado [] ResultadoField;

		private string codigoField;

		private string mensajeField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public Mictlanix.DFacture.Client.Internals.ListaResultado [] Resultado {
			get {
				return this.ResultadoField;
			}
			set {
				this.ResultadoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string mensaje {
			get {
				return this.mensajeField;
			}
			set {
				this.mensajeField = value;
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.Runtime.Serialization", "3.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute (Name = "ListaResultado", Namespace = "http://schemas.datacontract.org/2004/07/TimbradoSOAP.Models")]
	internal partial class ListaResultado : object, System.Runtime.Serialization.IExtensibleDataObject {

		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		private string codigoField;

		private string respuestaField;

		private string uuidField;

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
			get {
				return this.extensionDataField;
			}
			set {
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string codigo {
			get {
				return this.codigoField;
			}
			set {
				this.codigoField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string respuesta {
			get {
				return this.respuestaField;
			}
			set {
				this.respuestaField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute ()]
		public string uuid {
			get {
				return this.uuidField;
			}
			set {
				this.uuidField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.ServiceModel", "3.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute (ConfigurationName = "Mictlanix.DFacture.Client.Internals.IWSTimbradoSOAP")]
	internal interface IWSTimbradoSOAP {

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDI33", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDI33Response")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarCFDI33 (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDI33Big", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDI33BigResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarCFDI33Big (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarCFDI (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarRetenciones", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarRetencionesResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarRetenciones (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/AcuseCancelacion", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/AcuseCancelacionResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaAcuse AcuseCancelacion (string user, string password, string uuid);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/RecuperarXML", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/RecuperarXMLResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaRecuperarXML RecuperarXML (string user, string password, string uuid);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/ConsultarTimbres", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/ConsultarTimbresResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaConsultarTimbres ConsultarTimbres (string user, string password);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/RegistrarAdquiriente", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/RegistrarAdquirienteResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaRegistrarAdquiriente RegistrarAdquiriente (string user, string password, string rfc, string certificado, string llave, string password_llave);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarSectorPrimario", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarSectorPrimarioResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarSectorPrimario (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/TimbrarSectorPrimario33", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/TimbrarSectorPrimario33Response")]
		Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarSectorPrimario33 (string user, string password, string xml);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDIPFX", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDIPFXResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarCFDIPFX (string user, string password, string rfc, string uuid, string pfx, string password_llave);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/AcuseComprobante", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/AcuseComprobanteResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaAcuse AcuseComprobante (string user, string password, string uuid);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/FirmaManifiesto", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/FirmaManifiestoResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaFirmaManifiesto FirmaManifiesto (string user, string password, string rfc, string nombre, string llave, string password_llave);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/CancelacionRetenciones", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/CancelacionRetencionesResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelacionRetenciones (string user, string password, string rfc, string uuid, string password_pfx);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/SubirPFX", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/SubirPFXResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaServicio SubirPFX (string user, string password, string rfc, string pfx);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/CancelarSectorprimario", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/CancelarSectorprimarioResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarSectorprimario (string user, string password, string rfc, string uuid);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/SolicitarTokenConfirmacion", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/SolicitarTokenConfirmacionResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaSolicitarToken SolicitarTokenConfirmacion (string user, string password, Mictlanix.DFacture.Client.Internals.DatosReferencia [] Referencia);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/EnviarTokenConfirmacion", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/EnviarTokenConfirmacionResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaEnviarToken EnviarTokenConfirmacion (string user, string password, string Token, string ResultadoCaptcha);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDISoap", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDISoapResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarCFDISoap (string user, string password, string mensaje);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/ConsultarEstatusCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/ConsultarEstatusCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaConsultarEstatusCFDI ConsultarEstatusCFDI (string user, string password, string rfcEmisor, string rfcReceptor, string total, string uuid);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/CancelarCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaCancelacionCFDI CancelarCFDI (string user, string password, string rfcEmisor, string rfcReceptor, string uuid, string total, string certificado, string llave, string password_llave);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/ConsultarRelacionadosCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/ConsultarRelacionadosCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaConsultarRelacionadosCFDI ConsultarRelacionadosCFDI (string user, string password, string uuid, string rfc, string certificado, string llave, string password_llave);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/ConsultarPendientesCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/ConsultarPendientesCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaConsultarPendientesCFDI ConsultarPendientesCFDI (string user, string password, string rfcReceptor);

		[System.ServiceModel.OperationContractAttribute (Action = "http://tempuri.org/IWSTimbradoSOAP/AceptacionRechazoCFDI", ReplyAction = "http://tempuri.org/IWSTimbradoSOAP/AceptacionRechazoCFDIResponse")]
		Mictlanix.DFacture.Client.Internals.RespuestaAceptacionRechazoCFDI AceptacionRechazoCFDI (string user, string password, string rfc, string certificado, string llave, string password_llave, string aceptacion, string rechazo);
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.ServiceModel", "3.0.0.0")]
	internal interface IWSTimbradoSOAPChannel : Mictlanix.DFacture.Client.Internals.IWSTimbradoSOAP, System.ServiceModel.IClientChannel {
	}

	[System.Diagnostics.DebuggerStepThroughAttribute ()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute ("System.ServiceModel", "3.0.0.0")]
	internal partial class WSTimbradoSOAPClient : System.ServiceModel.ClientBase<Mictlanix.DFacture.Client.Internals.IWSTimbradoSOAP>, Mictlanix.DFacture.Client.Internals.IWSTimbradoSOAP {

		public WSTimbradoSOAPClient ()
		{
		}

		public WSTimbradoSOAPClient (string endpointConfigurationName) :
			base (endpointConfigurationName)
		{
		}

		public WSTimbradoSOAPClient (string endpointConfigurationName, string remoteAddress) :
			base (endpointConfigurationName, remoteAddress)
		{
		}

		public WSTimbradoSOAPClient (string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
			base (endpointConfigurationName, remoteAddress)
		{
		}

		public WSTimbradoSOAPClient (System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
			base (binding, remoteAddress)
		{
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarCFDI33 (string user, string password, string xml)
		{
			return base.Channel.TimbrarCFDI33 (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarCFDI33Big (string user, string password, string xml)
		{
			return base.Channel.TimbrarCFDI33Big (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarCFDI (string user, string password, string xml)
		{
			return base.Channel.TimbrarCFDI (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarRetenciones (string user, string password, string xml)
		{
			return base.Channel.TimbrarRetenciones (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaAcuse AcuseCancelacion (string user, string password, string uuid)
		{
			return base.Channel.AcuseCancelacion (user, password, uuid);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaRecuperarXML RecuperarXML (string user, string password, string uuid)
		{
			return base.Channel.RecuperarXML (user, password, uuid);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaConsultarTimbres ConsultarTimbres (string user, string password)
		{
			return base.Channel.ConsultarTimbres (user, password);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaRegistrarAdquiriente RegistrarAdquiriente (string user, string password, string rfc, string certificado, string llave, string password_llave)
		{
			return base.Channel.RegistrarAdquiriente (user, password, rfc, certificado, llave, password_llave);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD TimbrarSectorPrimario (string user, string password, string xml)
		{
			return base.Channel.TimbrarSectorPrimario (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaTFD33 TimbrarSectorPrimario33 (string user, string password, string xml)
		{
			return base.Channel.TimbrarSectorPrimario33 (user, password, xml);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarCFDIPFX (string user, string password, string rfc, string uuid, string pfx, string password_llave)
		{
			return base.Channel.CancelarCFDIPFX (user, password, rfc, uuid, pfx, password_llave);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaAcuse AcuseComprobante (string user, string password, string uuid)
		{
			return base.Channel.AcuseComprobante (user, password, uuid);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaFirmaManifiesto FirmaManifiesto (string user, string password, string rfc, string nombre, string llave, string password_llave)
		{
			return base.Channel.FirmaManifiesto (user, password, rfc, nombre, llave, password_llave);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelacionRetenciones (string user, string password, string rfc, string uuid, string password_pfx)
		{
			return base.Channel.CancelacionRetenciones (user, password, rfc, uuid, password_pfx);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaServicio SubirPFX (string user, string password, string rfc, string pfx)
		{
			return base.Channel.SubirPFX (user, password, rfc, pfx);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarSectorprimario (string user, string password, string rfc, string uuid)
		{
			return base.Channel.CancelarSectorprimario (user, password, rfc, uuid);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaSolicitarToken SolicitarTokenConfirmacion (string user, string password, Mictlanix.DFacture.Client.Internals.DatosReferencia [] Referencia)
		{
			return base.Channel.SolicitarTokenConfirmacion (user, password, Referencia);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaEnviarToken EnviarTokenConfirmacion (string user, string password, string Token, string ResultadoCaptcha)
		{
			return base.Channel.EnviarTokenConfirmacion (user, password, Token, ResultadoCaptcha);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaCancelacion CancelarCFDISoap (string user, string password, string mensaje)
		{
			return base.Channel.CancelarCFDISoap (user, password, mensaje);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaConsultarEstatusCFDI ConsultarEstatusCFDI (string user, string password, string rfcEmisor, string rfcReceptor, string total, string uuid)
		{
			return base.Channel.ConsultarEstatusCFDI (user, password, rfcEmisor, rfcReceptor, total, uuid);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaCancelacionCFDI CancelarCFDI (string user, string password, string rfcEmisor, string rfcReceptor, string uuid, string total, string certificado, string llave, string password_llave)
		{
			return base.Channel.CancelarCFDI (user, password, rfcEmisor, rfcReceptor, uuid, total, certificado, llave, password_llave);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaConsultarRelacionadosCFDI ConsultarRelacionadosCFDI (string user, string password, string uuid, string rfc, string certificado, string llave, string password_llave)
		{
			return base.Channel.ConsultarRelacionadosCFDI (user, password, uuid, rfc, certificado, llave, password_llave);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaConsultarPendientesCFDI ConsultarPendientesCFDI (string user, string password, string rfcReceptor)
		{
			return base.Channel.ConsultarPendientesCFDI (user, password, rfcReceptor);
		}

		public Mictlanix.DFacture.Client.Internals.RespuestaAceptacionRechazoCFDI AceptacionRechazoCFDI (string user, string password, string rfc, string certificado, string llave, string password_llave, string aceptacion, string rechazo)
		{
			return base.Channel.AceptacionRechazoCFDI (user, password, rfc, certificado, llave, password_llave, aceptacion, rechazo);
		}
	}
}
